# m = [10,8,99,15]
# print(m)
# print(type(m))
# print(m[0])
# print(m[1])
# print(m[2])
# print(m[3])

# print(m[-3]) # Negative index
# print(m[len(m)-3]) # Positive index
# print(m[4-3]) # Positive index
# print(m[2]) # Positive index

# if "10" in m:
#   print("Yes")
# else:
#   print("No")

# Same thing applies for strings as well!
# if "Car" in "Cartoon:
#   print("Yes")

# print(m[0:7])
# print(m[1:9])
# print(m[1:9:3])

# lst = [i*i for i in range(10)]
# print(lst)
# lst = [i*i for i in range(10) if i%2==0]
# print(lst)

 #METHODS

m=[50,60,20,48,23,1,2,3,4,9,11,'HI','HELLO']
#print(m[::-1])
#print(m)
#m=[9,8,1,5,7,2]
#l=[10,9,1]
#l.insert(3,20) index,value
#l=ms reference of m , m value changes if we change l value
#l.copy(m) copies m list without changing its values
#l.append(2)
#l.extend(m)
#k=l+m
#print(k)